# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditCity = QtWidgets.QLineEdit(Form)
        self.lineEditCity.setObjectName("lineEditCity")
        self.horizontalLayout.addWidget(self.lineEditCity)
        self.btnSearch = QtWidgets.QPushButton(Form)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelTemp = QtWidgets.QLabel(Form)
        self.labelTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemp.setObjectName("labelTemp")
        self.verticalLayout.addWidget(self.labelTemp)
        self.labelCondition = QtWidgets.QLabel(Form)
        self.labelCondition.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCondition.setObjectName("labelCondition")
        self.verticalLayout.addWidget(self.labelCondition)
        self.labelHumidity = QtWidgets.QLabel(Form)
        self.labelHumidity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHumidity.setObjectName("labelHumidity")
        self.verticalLayout.addWidget(self.labelHumidity)
        self.labelWind = QtWidgets.QLabel(Form)
        self.labelWind.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWind.setObjectName("labelWind")
        self.verticalLayout.addWidget(self.labelWind)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Weather App"))
        self.lineEditCity.setPlaceholderText(_translate("Form", "Enter city name"))
        self.btnSearch.setText(_translate("Form", "Search"))
        self.labelTemp.setText(_translate("Form", "Temperature: --"))
        self.labelCondition.setText(_translate("Form", "Condition: --"))
        self.labelHumidity.setText(_translate("Form", "Humidity: --"))
        self.labelWind.setText(_translate("Form", "Wind: --"))
